/**
 * QueryBuilderApi
 * Active Query Builder Web API lets create, analyze and modify SQL queries for different database servers using RESTful HTTP requests to a cloud-based service. It requires SQL execution context (information about database schema and used database server) to be stored under the registered account at https://webapi.activequerybuilder.com/.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@activedbsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package webapi.activequerybuilder.api;

import webapi.activequerybuilder.ApiException;
import webapi.activequerybuilder.model.SqlQuery;
import webapi.activequerybuilder.model.QueryColumn;
import webapi.activequerybuilder.model.Transform;
import webapi.activequerybuilder.model.TransformResult;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ActiveQueryBuilderApi
 */
public class ActiveQueryBuilderApiTest {

    private final ActiveQueryBuilderApi api = new ActiveQueryBuilderApi();

    
    /**
     * 
     *
     * Returns list of columns for the given SQL query.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getQueryColumnsPostTest() throws ApiException {
        SqlQuery query = null;
        // List<QueryColumn> response = api.getQueryColumnsPost(query);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Transforms the given SQL query according to the commands provided in this request. You can add constraints, hide some of the resultset columns, chang sorting or limit rows of resultset. All transformations can only lead to reorganization or limitation of the resultset data. This means that it&#39;s impossible to get transformed SQL that reveals any other data than the data retutned by original query.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transformSQLPostTest() throws ApiException {
        Transform transform = null;
        // TransformResult response = api.transformSQLPost(transform);

        // TODO: test validations
    }
    
}
